import { districtData } from '../data/appContent';

interface DistrictMetricsProps {
  totalHighRisk: number;
  referralsSent: number;
  ancFollowUp: number;
}

export function DistrictMetrics({
  totalHighRisk,
  referralsSent,
  ancFollowUp,
}: DistrictMetricsProps) {
  return (
    <div className="space-y-8">
      <div className="grid gap-6 md:grid-cols-3">
        <div className="rounded-3xl border border-slate-800 bg-slate-900/80 p-6 shadow-xl shadow-slate-950/20">
          <p className="text-sm uppercase tracking-[0.3em] text-slate-400">High-risk cases</p>
          <p className="mt-3 text-4xl font-bold text-white">{totalHighRisk}</p>
          <p className="mt-2 text-slate-300">Critical patients identified across rural districts.</p>
        </div>
        <div className="rounded-3xl border border-slate-800 bg-slate-900/80 p-6 shadow-xl shadow-slate-950/20">
          <p className="text-sm uppercase tracking-[0.3em] text-slate-400">Referrals sent</p>
          <p className="mt-3 text-4xl font-bold text-white">{referralsSent}</p>
          <p className="mt-2 text-slate-300">Referrals generated by CHWs for clinic follow-up.</p>
        </div>
        <div className="rounded-3xl border border-slate-800 bg-slate-900/80 p-6 shadow-xl shadow-slate-950/20">
          <p className="text-sm uppercase tracking-[0.3em] text-slate-400">ANC follow-up rate</p>
          <p className="mt-3 text-4xl font-bold text-white">{ancFollowUp}%</p>
          <p className="mt-2 text-slate-300">Women returning for antenatal care after alerts.</p>
        </div>
      </div>
      <div className="rounded-3xl border border-slate-800 bg-slate-900/80 p-8 shadow-xl shadow-slate-950/30">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <h4 className="text-xl font-semibold text-white">Risk cases by district</h4>
            <p className="mt-2 text-slate-400">Synthetic district distribution for the demo.</p>
          </div>
          <div className="rounded-full bg-slate-800 px-4 py-2 text-sm text-slate-200">Updated today</div>
        </div>
        <div className="mt-8 space-y-5">
          {districtData.map((item) => (
            <div key={item.district} className="space-y-2">
              <div className="flex items-center justify-between text-sm text-slate-300">
                <span>{item.district}</span>
                <span>{item.cases} cases</span>
              </div>
              <div className="h-4 overflow-hidden rounded-full bg-slate-800">
                <div
                  className="h-full rounded-full bg-sky-500 transition-all"
                  style={{ width: `${(item.cases / 10) * 100}%` }}
                />
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
